#include<fstream>
#include<iostream>
#include<vector>
#include<stdio.h>
#include<limits>
#include<algorithm>
#include<iterator>
#include<iomanip>
#include<stdlib.h>
#include<stack>
#include<memory> 
#include<map>
#include<list>
#include<string>